/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;
import Game.*;
import View.*;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.sound.sampled.UnsupportedAudioFileException;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.UIManager;


/**
 *
 * @author Microsoft
 */
public class MainMenu extends javax.swing.JFrame {
    int mouseX , mouseY;
    /**
     * Creates new form MainMenu
     */
    public MainMenu() {
        try {
           UIManager.setLookAndFeel(new com.jtattoo.plaf.graphite.GraphiteLookAndFeel());
        }catch (Exception e) {
            //
        }
        initComponents();
        this.setVisible(true);
        
    }

   
    
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Piece = new javax.swing.JPopupMenu();
        Queen = new javax.swing.JMenuItem();
        Rook = new javax.swing.JMenuItem();
        Pawn = new javax.swing.JMenuItem();
        popupMenu1 = new java.awt.PopupMenu();
        menu1 = new java.awt.Menu();
        menuItem1 = new java.awt.MenuItem();
        topbar = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        container = new javax.swing.JPanel();
        menu = new javax.swing.JPanel();
        whitePlayerPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        whiteNama = new javax.swing.JLabel();
        whiteWon = new javax.swing.JLabel();
        whitePlayed = new javax.swing.JLabel();
        blackPlayerPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        blackWon = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        blackNama = new javax.swing.JLabel();
        blackPlayed = new javax.swing.JLabel();
        utilities = new javax.swing.JPanel();
        turnInfo = new javax.swing.JLabel();
        timer = new javax.swing.JLabel();
        btnPanel1 = new javax.swing.JPanel();
        undoBtn = new javax.swing.JButton();
        board = new javax.swing.JPanel();

        Queen.setText("Queen");
        Piece.add(Queen);

        Rook.setText("Rook");
        Piece.add(Rook);

        Pawn.setText("Pawn");
        Piece.add(Pawn);

        popupMenu1.setLabel("popupMenu1");

        menu1.setLabel("menu1");

        menuItem1.setLabel("menuItem1");
        menu1.add(menuItem1);

        popupMenu1.add(menu1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("AChees");
        setBackground(new java.awt.Color(53, 55, 56));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        setForeground(new java.awt.Color(186, 186, 186));
        setLocationByPlatform(true);
        setModalExclusionType(java.awt.Dialog.ModalExclusionType.APPLICATION_EXCLUDE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        topbar.setBackground(new java.awt.Color(42, 44, 45));
        topbar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                topbarMouseDragged(evt);
            }
        });
        topbar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                topbarMousePressed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 3, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(230, 145, 44));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ChessGame/images/icons8_knight_40px.png"))); // NOI18N
        jLabel4.setText("AChess");

        javax.swing.GroupLayout topbarLayout = new javax.swing.GroupLayout(topbar);
        topbar.setLayout(topbarLayout);
        topbarLayout.setHorizontalGroup(
            topbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, topbarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(980, Short.MAX_VALUE))
        );
        topbarLayout.setVerticalGroup(
            topbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        getContentPane().add(topbar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, 50));

        container.setPreferredSize(new java.awt.Dimension(1200, 650));
        container.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        menu.setBackground(new java.awt.Color(39, 37, 34));
        menu.setAlignmentX(5.0F);
        menu.setLayout(new java.awt.GridLayout(3, 1));

        whitePlayerPanel.setBackground(new java.awt.Color(57, 59, 61));
        whitePlayerPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        whitePlayerPanel.setForeground(java.awt.Color.white);
        whitePlayerPanel.setComponentPopupMenu(Piece);
        whitePlayerPanel.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        whitePlayerPanel.setPreferredSize(new java.awt.Dimension(400, 150));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(230, 145, 44));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("White Player");

        jLabel3.setBackground(new java.awt.Color(58, 61, 63));
        jLabel3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(183, 183, 183));
        jLabel3.setText("Name");

        jLabel6.setBackground(new java.awt.Color(58, 61, 63));
        jLabel6.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(183, 183, 183));
        jLabel6.setText("Won");

        jLabel7.setBackground(new java.awt.Color(58, 61, 63));
        jLabel7.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(183, 183, 183));
        jLabel7.setText("Games Played");

        whiteNama.setBackground(new java.awt.Color(58, 61, 63));
        whiteNama.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        whiteNama.setForeground(new java.awt.Color(183, 183, 183));
        whiteNama.setText("Kadek");

        whiteWon.setBackground(new java.awt.Color(58, 61, 63));
        whiteWon.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        whiteWon.setForeground(new java.awt.Color(183, 183, 183));
        whiteWon.setText("Kadek");

        whitePlayed.setBackground(new java.awt.Color(58, 61, 63));
        whitePlayed.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        whitePlayed.setForeground(new java.awt.Color(183, 183, 183));
        whitePlayed.setText("Kadek");

        javax.swing.GroupLayout whitePlayerPanelLayout = new javax.swing.GroupLayout(whitePlayerPanel);
        whitePlayerPanel.setLayout(whitePlayerPanelLayout);
        whitePlayerPanelLayout.setHorizontalGroup(
            whitePlayerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(whitePlayerPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(whitePlayerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 392, Short.MAX_VALUE)
                    .addGroup(whitePlayerPanelLayout.createSequentialGroup()
                        .addGroup(whitePlayerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)
                        .addGroup(whitePlayerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(whiteNama, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(whiteWon, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(whitePlayed, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        whitePlayerPanelLayout.setVerticalGroup(
            whitePlayerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(whitePlayerPanelLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(whitePlayerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(whiteNama, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(whitePlayerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(whiteWon, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(whitePlayerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(whitePlayed, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        menu.add(whitePlayerPanel);

        blackPlayerPanel.setBackground(new java.awt.Color(57, 59, 61));
        blackPlayerPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        blackPlayerPanel.setForeground(java.awt.Color.white);
        blackPlayerPanel.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(230, 145, 44));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Black Player");

        blackWon.setBackground(new java.awt.Color(58, 61, 63));
        blackWon.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        blackWon.setForeground(new java.awt.Color(183, 183, 183));
        blackWon.setText("Kadek");

        jLabel9.setBackground(new java.awt.Color(58, 61, 63));
        jLabel9.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(183, 183, 183));
        jLabel9.setText("Won");

        jLabel10.setBackground(new java.awt.Color(58, 61, 63));
        jLabel10.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(183, 183, 183));
        jLabel10.setText("Games Played");

        jLabel11.setBackground(new java.awt.Color(58, 61, 63));
        jLabel11.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(183, 183, 183));
        jLabel11.setText("Name");

        blackNama.setBackground(new java.awt.Color(58, 61, 63));
        blackNama.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        blackNama.setForeground(new java.awt.Color(183, 183, 183));
        blackNama.setText("Kadek");

        blackPlayed.setBackground(new java.awt.Color(58, 61, 63));
        blackPlayed.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        blackPlayed.setForeground(new java.awt.Color(183, 183, 183));
        blackPlayed.setText("Kadek");

        javax.swing.GroupLayout blackPlayerPanelLayout = new javax.swing.GroupLayout(blackPlayerPanel);
        blackPlayerPanel.setLayout(blackPlayerPanelLayout);
        blackPlayerPanelLayout.setHorizontalGroup(
            blackPlayerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(blackPlayerPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(blackPlayerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 386, Short.MAX_VALUE)
                    .addGroup(blackPlayerPanelLayout.createSequentialGroup()
                        .addGroup(blackPlayerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(blackPlayerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(blackWon, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(blackPlayed, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(blackNama, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        blackPlayerPanelLayout.setVerticalGroup(
            blackPlayerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(blackPlayerPanelLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(blackPlayerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(blackNama, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(blackPlayerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(blackWon, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(blackPlayerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(blackPlayed, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(38, Short.MAX_VALUE))
        );

        menu.add(blackPlayerPanel);

        utilities.setBackground(new java.awt.Color(57, 59, 61));
        utilities.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        utilities.setForeground(java.awt.Color.white);

        turnInfo.setFont(new java.awt.Font("Segoe UI", 2, 32)); // NOI18N
        turnInfo.setForeground(new java.awt.Color(255, 172, 37));
        turnInfo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        turnInfo.setText("WHITE PLAYER");

        timer.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        timer.setForeground(new java.awt.Color(183, 183, 183));
        timer.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        btnPanel1.setBackground(new java.awt.Color(230, 145, 44));

        undoBtn.setBackground(new java.awt.Color(226, 143, 43));
        undoBtn.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        undoBtn.setForeground(java.awt.Color.white);
        undoBtn.setText("Undo");
        undoBtn.setBorder(null);
        undoBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        undoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                undoBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout btnPanel1Layout = new javax.swing.GroupLayout(btnPanel1);
        btnPanel1.setLayout(btnPanel1Layout);
        btnPanel1Layout.setHorizontalGroup(
            btnPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(undoBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
        );
        btnPanel1Layout.setVerticalGroup(
            btnPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(undoBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout utilitiesLayout = new javax.swing.GroupLayout(utilities);
        utilities.setLayout(utilitiesLayout);
        utilitiesLayout.setHorizontalGroup(
            utilitiesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(timer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(utilitiesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(turnInfo, javax.swing.GroupLayout.DEFAULT_SIZE, 374, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(utilitiesLayout.createSequentialGroup()
                .addGap(119, 119, 119)
                .addComponent(btnPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        utilitiesLayout.setVerticalGroup(
            utilitiesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, utilitiesLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(turnInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(timer, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );

        menu.add(utilities);

        container.add(menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 0, 400, 600));

        board.setBackground(new java.awt.Color(255, 255, 255));
        board.setForeground(new java.awt.Color(255, 255, 255));
        board.setComponentPopupMenu(Piece);
        board.setPreferredSize(new java.awt.Dimension(800, 600));
        board.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                boardKeyPressed(evt);
            }
        });
        board.setLayout(new java.awt.GridLayout(8, 8));
        container.add(board, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 600));

        getContentPane().add(container, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 1200, 600));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void topbarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_topbarMousePressed
        mouseX = evt.getX();
        mouseY = evt.getY();
    }//GEN-LAST:event_topbarMousePressed

    private void topbarMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_topbarMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        
        this.setLocation(x-mouseX, y-mouseY);
    }//GEN-LAST:event_topbarMouseDragged

    private void boardKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_boardKeyPressed
        
    }//GEN-LAST:event_boardKeyPressed

    private void undoBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_undoBtnActionPerformed
        // TODO add your handling code here:
        if (Controller.canUndo == true) {
//            this.disable();
//            UpgradeHandler a = new UpgradeHandler(this,false,this);
            
//            this.disable();
//            a.setVisible(true);
            try {
                Controller.undoMove();
            } catch (UnsupportedAudioFileException ex) {
                Logger.getLogger(MainMenu.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
                Logger.getLogger(MainMenu.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_undoBtnActionPerformed
 
    
    public static JPanel getBoard() {
        return board;
    }

    public JPanel getContainer() {
        return container;
    }
    
    public int getMouseX() {
        return mouseX;
    }

    public int getMouseY() {
        return mouseY;
    }

    public JLabel getBlackNama() {
        return blackNama;
    }

    public void setBlackNama(JLabel blackNama) {
        this.blackNama = blackNama;
    }

    public JButton getUndoBtn() {
        return undoBtn;
    }

    public void setUndoBtn(JButton undoBtn) {
        this.undoBtn = undoBtn;
    }
    
    public JLabel getBlackPlayed() {
        return blackPlayed;
    }

    public void setBlackPlayed(JLabel blackPlayed) {
        this.blackPlayed = blackPlayed;
    }

    public JPanel getBlackPlayerPanel() {
        return blackPlayerPanel;
    }

    public void setBlackPlayerPanel(JPanel blackPlayerPanel) {
        this.blackPlayerPanel = blackPlayerPanel;
    }

    public JLabel getBlackWon() {
        return blackWon;
    }

    public void setBlackWon(JLabel blackWon) {
        this.blackWon = blackWon;
    }

    public JLabel getjLabel1() {
        return jLabel1;
    }

    public void setjLabel1(JLabel jLabel1) {
        this.jLabel1 = jLabel1;
    }

    public JLabel getjLabel10() {
        return jLabel10;
    }

    public void setjLabel10(JLabel jLabel10) {
        this.jLabel10 = jLabel10;
    }

    public JLabel getjLabel11() {
        return jLabel11;
    }

    public void setjLabel11(JLabel jLabel11) {
        this.jLabel11 = jLabel11;
    }

    public JLabel getjLabel2() {
        return jLabel2;
    }

    public void setjLabel2(JLabel jLabel2) {
        this.jLabel2 = jLabel2;
    }

    public JLabel getjLabel3() {
        return jLabel3;
    }

    public void setjLabel3(JLabel jLabel3) {
        this.jLabel3 = jLabel3;
    }

    public JLabel getjLabel4() {
        return jLabel4;
    }

    public void setjLabel4(JLabel jLabel4) {
        this.jLabel4 = jLabel4;
    }

    public JLabel getjLabel6() {
        return jLabel6;
    }

    public void setjLabel6(JLabel jLabel6) {
        this.jLabel6 = jLabel6;
    }

    public JLabel getjLabel7() {
        return jLabel7;
    }

    public void setjLabel7(JLabel jLabel7) {
        this.jLabel7 = jLabel7;
    }

    public JLabel getjLabel9() {
        return jLabel9;
    }

    public void setjLabel9(JLabel jLabel9) {
        this.jLabel9 = jLabel9;
    }

//    public JLabel getLabelUndo() {
//        return labelUndo;
//    }
//
//    public void setLabelUndo(JLabel labelUndo) {
//        this.labelUndo = labelUndo;
//    }

    public JPanel getMenu() {
        return menu;
    }

    public void setMenu(JPanel menu) {
        this.menu = menu;
    }

    public static JLabel getTimer() {
        return timer;
    }

    public static void setTimer(JLabel timer) {
        MainMenu.timer = timer;
    }

    public JPanel getTopbar() {
        return topbar;
    }

    public void setTopbar(JPanel topbar) {
        this.topbar = topbar;
    }

    public static JLabel getTurnInfo() {
        return turnInfo;
    }

    public static void setTurnInfo(JLabel turnInfo) {
        MainMenu.turnInfo = turnInfo;
    }

    public JPanel getUtilities() {
        return utilities;
    }

    public void setUtilities(JPanel utilities) {
        this.utilities = utilities;
    }

    public JLabel getWhiteNama() {
        return whiteNama;
    }

    public void setWhiteNama(JLabel whiteNama) {
        this.whiteNama = whiteNama;
    }

    public JLabel getWhitePlayed() {
        return whitePlayed;
    }

    public void setWhitePlayed(JLabel whitePlayed) {
        this.whitePlayed = whitePlayed;
    }

    public JPanel getWhitePlayerPanel() {
        return whitePlayerPanel;
    }

    public void setWhitePlayerPanel(JPanel whitePlayerPanel) {
        this.whitePlayerPanel = whitePlayerPanel;
    }

    public JLabel getWhiteWon() {
        return whiteWon;
    }

    public void setWhiteWon(JLabel whiteWon) {
        this.whiteWon = whiteWon;
    }
    
    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Pawn;
    private javax.swing.JPopupMenu Piece;
    private javax.swing.JMenuItem Queen;
    private javax.swing.JMenuItem Rook;
    private javax.swing.JLabel blackNama;
    private javax.swing.JLabel blackPlayed;
    private javax.swing.JPanel blackPlayerPanel;
    private javax.swing.JLabel blackWon;
    private static javax.swing.JPanel board;
    private javax.swing.JPanel btnPanel1;
    private javax.swing.JPanel container;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel menu;
    private java.awt.Menu menu1;
    private java.awt.MenuItem menuItem1;
    private java.awt.PopupMenu popupMenu1;
    private static javax.swing.JLabel timer;
    private javax.swing.JPanel topbar;
    private static javax.swing.JLabel turnInfo;
    private javax.swing.JButton undoBtn;
    private javax.swing.JPanel utilities;
    private javax.swing.JLabel whiteNama;
    private javax.swing.JLabel whitePlayed;
    private javax.swing.JPanel whitePlayerPanel;
    private javax.swing.JLabel whiteWon;
    // End of variables declaration//GEN-END:variables
}
