package View;
import java.awt.event.*;
import javax.swing.JButton;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Microsoft
 */
public class Upgrade extends javax.swing.JDialog{

    /**
     * Creates new form Upgrade
     * @param parent
     * @param modal
     */
    public Upgrade(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        try {
           UIManager.setLookAndFeel(new com.jtattoo.plaf.graphite.GraphiteLookAndFeel());
        }catch (UnsupportedLookAndFeelException e) {
            //
        }
        this.setVisible(true);
        initComponents();
    }
    
    public void addActionListener (ActionListener ae) {
        this.bishop.addActionListener(ae);
        this.knight.addActionListener(ae);
        this.pawn.addActionListener(ae);
        this.queen.addActionListener(ae);
        this.rook.addActionListener(ae);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        queen = new javax.swing.JButton();
        rook = new javax.swing.JButton();
        bishop = new javax.swing.JButton();
        knight = new javax.swing.JButton();
        pawn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setBackground(new java.awt.Color(153, 153, 153));
        setMinimumSize(new java.awt.Dimension(152, 600));
        setResizable(false);
        getContentPane().setLayout(new java.awt.GridLayout(5, 1));

        queen.setBackground(new java.awt.Color(153, 153, 153));
        getContentPane().add(queen);

        rook.setBackground(new java.awt.Color(153, 153, 153));
        getContentPane().add(rook);

        bishop.setBackground(new java.awt.Color(153, 153, 153));
        getContentPane().add(bishop);

        knight.setBackground(new java.awt.Color(153, 153, 153));
        getContentPane().add(knight);

        pawn.setBackground(new java.awt.Color(153, 153, 153));
        getContentPane().add(pawn);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    
    public JButton getBishop() {
        return bishop;
    }

    public void setBishop(JButton bishop) {
        this.bishop = bishop;
    }

    public JButton getKnight() {
        return knight;
    }

    public void setKnight(JButton knight) {
        this.knight = knight;
    }

    public JButton getPawn() {
        return pawn;
    }

    public void setPawn(JButton pawn) {
        this.pawn = pawn;
    }

    public JButton getQueen() {
        return queen;
    }

    public void setQueen(JButton queen) {
        this.queen = queen;
    }

    public JButton getRook() {
        return rook;
    }

    public void setRook(JButton rook) {
        this.rook = rook;
    }
    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bishop;
    private javax.swing.JButton knight;
    private javax.swing.JButton pawn;
    private javax.swing.JButton queen;
    private javax.swing.JButton rook;
    // End of variables declaration//GEN-END:variables
}
